layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:categories/:slug/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 6
  exclude:
    archived: true
    forks: true

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: BSFishy
  # instagram: your_username
  # keybase: your_username
  linkedin: matt-provost
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 4254252
  # telegram: your_username
  twitter: BSFishy
  # unsplash: your_username
  # vk: your_username
  website: https://bsfishy.github.io/
  # youtube: your_username

topics:
  - name: C
    web_url: https://github.com/topics/c
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/c/c.png
  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/cpp/cpp.png
  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
  - name: Swift
    web_url: https://github.com/topics/swift
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/swift/swift.png
  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png
  - name: Unity
    web_url: https://github.com/topics/unity
  - name: Front end development
    web_url: https://github.com/topics/frontend
  - name: Deep learning
    web_url: https://github.com/topics/deep-learning
